### ISSUE TITLE
[FEATURE] 마이페이지 기능구현

### ISSUE THREAD

**Issue by Jay127127** [devitssu/helloffice#102]
# 기능 설명
마이페이지 수정

# To-do
- [ ] 사원정보 가져오기
- [ ] 화면 오류나는 부분 해결

# ETC
- [ ] ## 부서리스트 수정 - 오류
- [ ] ## 부서리스트 > 전체 - 오류
