### ISSUE TITLE
[STYLE]연차 사용 촉구서 게시판 관련 UI

### ISSUE THREAD

**Issue by thespeace** [devitssu/helloffice#104]
# 설명
관리자/사원의 연차 사용 촉구 관련 UI와 연차 정산 관련 UI

# To-do
- [ ] 관리자용 연차 사용 촉구 게시판 UI
- [ ] 사원용 연차 사용 촉구 확인용 Modal
- [ ] 사원용 남은 연차 정산 게시판 UI
- [ ] 관리자용 연차 정산 게시판 UI

# ETC
