### ISSUE TITLE
[FEATURE] 승인테이블 추가, 양식 수정

### ISSUE THREAD

**Issue by lecharl** [devitssu/helloffice#117]
# 기능 설명
- 승인테이블 추가, 양식 수정

# To-do
- [x] 승인테이블 추가에 따른 양식 테이블 수정
- [x] 승인자 데이터 받아오기
- [x] 받은 승인자 데이터를 select
- [x] 승인 UI 오류 해결

# ETC
- 이벤트 누적 현상 : 이유는 모르겠으나, 해당 요소의 누적된 이벤트를 제거하고 다시 이벤트를 실행하면 된다. 
-> `$(document).off('이벤트', '요소').on('이벤트', '요소', function(){})`
