### ISSUE TITLE
[FEATURE] 메시지 보낼 대상 검색, 메인 화면 메시지 카드

### ISSUE THREAD

**Issue by devitssu** [devitssu/helloffice#119]
# 기능 설명
보낼 대상 검색해서 채팅방 열기 및 메인화면 받은 메시지 카드에 최신 메시지 목록 보여주기

# To-do
- [ ] 검색해서 목록 보여주기
- [ ] 결과 목록을 통해 채팅 열기
- [ ] 메인 화면에 최신 메시지(채팅방) 3개 보여주기 

# ETC
