### ISSUE TITLE
[FEATURE] 승인자 데이터 상세 조회, 문서 데이터 받아오기

### ISSUE THREAD

**Issue by lecharl** [devitssu/helloffice#127]
# 기능 설명
- 승인자 데이터 상세 조회, 문서 데이터 받아오기

# To-do
- [ ] 양식 상세 조회 오류 해결
- [ ] 받은 승인자 데이터 상세 조회
- [ ] 문서 데이터 받아오기
- [ ] db 테이블 수정으로 인한 mapper 수정

# ETC
- 반복되는 부분은 함수로 처리하자.(예: 데이터를 담을 때 객체로 만들어주는 함수)
- select한 순서를 받아오는 건 쉽지 않다.  
-> 해결1: rownum부여 && 서브쿼리 사용. 그러나 제대로 작동하지 않을 때가 발생해서 문제가 생김.
-> 해결2: pk를 생성하자.
