### ISSUE TITLE
[FEATURE]문서, 문서승인관련 테이블 작성

### ISSUE THREAD

**Issue by lecharl** [devitssu/helloffice#134]
# 기능 설명
- 문서, 문서승인관련 테이블 작성

# To-do
- [ ] 문서 테이블 작성
- [ ] 문서승인 테이블 작성
- [ ] 각 테이블에 데이터 담기

# ETC
