### ISSUE TITLE
[FEATURE] 인사노트 // 휴가정보 

### ISSUE THREAD

**Issue by Jay127127** [devitssu/helloffice#145]
# 기능 설명
마이페이지 휴가 정보 연동시키거나 링크 연결하기 
인사노트 기능 구현

# To-do
- [ ] 휴가 정보 불러오기 
- [ ] 정보 불러오는게 힘들 것 같으면 링크 연결 시키기
- [ ] 인사노트 더미 데이터 만들어서 테스트 
- [ ] 가능하면 ajax로 해보기

# ETC
...
