### ISSUE TITLE
[STYLE]근무, 휴가 페이지 전체 레이아웃

### ISSUE THREAD

**Issue by thespeace** [devitssu/helloffice#18]
# 설명
근무, 휴가 페이지 UI구현

# To-do
- [x] 페이지 내부 상단 메뉴바
  > 내 스케줄
  > 구성원 스케줄
  > 주 단위 안내 바
  > 오늘
  > 휴가 신청 내역
  > 휴가 사용
- [x] 근무 및 유급 휴가 통합 간편 조회
- [x] 고정 출 퇴근
- [x] 반복 일정 등록
- [x] 이번 주 근무 조회

# ETC
