### ISSUE TITLE
[STYLE] 모달 화면 내부 구성 작업 

### ISSUE THREAD

**Issue by Jay127127** [devitssu/helloffice#22]
# 설명
hr 페이지에서 개인 정보 확인할 수 있는 모달창 내부 작업.

# To-do
- [ ] 좌상단 간단한 프로필 화면 작업
- [ ] 인사정보 페이지 작업
- [ ] 계약정보 페이지 작업
- [ ] 급여정보 페이지 작업

# ETC
