### ISSUE TITLE
[STYLE] 예약 페이지 UI

### ISSUE THREAD

**Issue by devitssu** [devitssu/helloffice#29]
# 설명
예약 페이지 UI 구현

# To-do
- [x] 예약 사이드바에 드롭다운으로 항목 추가
- [x] 예약 페이지 구현
- [x] 캘린더 라이브러리 연동

# ETC
