### ISSUE TITLE
[FEATURE] 부서리스트 작업

### ISSUE THREAD

**Issue by Jay127127** [devitssu/helloffice#80]
# 기능 설명
부서리스트 불러오면서 사원정보 끌어오기

# To-do
- [x] 디비 부서랑 사원 연결해서 데이터 가져오기 
- [x] 리스트 마다 사원 정보 넣기
- [ ] 부서 리스트 수정 기능 수정하기

# ETC
